### ISSUE TITLE
Geo Location not Stored in Database

### ISSUE THREAD

**Issue by techmatevaibhav** [voerro/laravel-visitor-tracker#1]
Hello i installed this Package and its was nice but i have issue with the country, city and lat, long.

How we can add location info as well ?

**Comment by AlexMordred** [comment]
Hi! Did you go through all the steps in the README? The "Installation - Geoapi" section describes how to start collecting the location info.

**Comment by techmatevaibhav** [comment]
Thank you for your reply yes I did all the step but for the location there no more clear step. Could you help me out with that.

**Comment by techmatevaibhav** [comment]
Thank you for your reply yes I did all the step but for the location there no more clear step. Could you help me out with that.

**Comment by AlexMordred** [comment]
Ok, can you tell me exactly what you did?

**Comment by techmatevaibhav** [comment]
I did all the step. But i don't know how to geo location work if you describe step for the geo.

**Comment by AlexMordred** [comment]
1) Go to the root directory of your project
2) Open `.env` and set `QUEUE_DRIVER=database`
3) Then open terminal inside the same directory and run these commands one after another:

```
php artisan queue:table
php artisan queue:failed-table
php artisan migrate
```

After that execute `php artisan queue:work` and keep the process running. This means you're not supposed to close the terminal window. I recommend you setting up the supervisor as described [here](https://laravel.com/docs/5.5/queues#supervisor-configuration) so you could close the window and so that the process gets restarted automatically in case it fails.

**Comment by techmatevaibhav** [comment]
Hey if i want to add custom Data using this plugin we can do that ?

**Comment by AlexMordred** [comment]
I don't think so, what do you mean? Did you manage to make the geolocation working?

**Comment by techmatevaibhav** [comment]
I have some different requirement and in that case i need to add Manually Log. we can do with this plugin or not ? 
and my Geo Location is still not working i follow all your step

**Comment by AlexMordred** [comment]
What do you need to log?

Sorry, I'm not sure what could be the problem if you've done all the steps. Do you have `jobs` and `jobs-failed` tables in your database? What happens when you run `php artisan queue:work`?

**Comment by techmatevaibhav** [comment]
it could be a anything to Log which is not in table. 

Yes i have both the table  no any error in failed job and in jobs table
vistitor table 
![image](https://user-images.githubusercontent.com/20147143/34779135-4960c190-f5ed-11e7-8786-74494009b0cd.png)

![image](https://user-images.githubusercontent.com/20147143/34779162-608c70e4-f5ed-11e7-9956-a0e31cc70c78.png)

**Comment by AlexMordred** [comment]
Seems like everything is working fine. Are you testing this on localhost? That might be a problem, because your API would be 127.0.0.1.

**Comment by AlexMordred** [comment]
You can't log additional info.

**Comment by techmatevaibhav** [comment]
Yes I am using on localhost may be that would be issue. I will check and update.

**Comment by ramyadavrp** [comment]
Hi,
I am also facing same issue even i have checked on https://127.0.0.1/  instead of https://localhost/.
And "php artisan queue:work" command is still running but Geo Location are not Storing in Database.
If any one help me it would be a great and appreciable support for me. 
Thanks
