### ISSUE TITLE
Track only some URI

### ISSUE THREAD

**Issue by cloudstudio** [voerro/laravel-visitor-tracker#10]
Hello ! thanks in advance.

I want track only 1 URI www.example.com/single/xxxxx no all pages, its posible ?

Another question, is posible create one more field ? for example link_id ?

Thanks !!!

**Comment by cloudstudio** [comment]
I create my own middleware just for this route, and overwrite Tracker class, but anyway i don't know if is easier to do.

Thanks !

**Comment by AlexMordred** [comment]
Sorry, it's not possible as of the moment. Generally, with stuff like this it would be present in the config file if it was possible. Anyway, I'm glad you were able to solve your problem.
