### ISSUE TITLE
It it possbile to dont_record by url mask (admin pages, etc) ?

### ISSUE THREAD

**Issue by Winnetu** [voerro/laravel-visitor-tracker#13]
Maybe in Tracker/shouldRecordRequest method:
                if ($field == 'url') {                    
                    if (preg_match('/'.$value.'/i', $data[$field]))
                        $conditionsMet++;
                } else 
                    if ($data[$field] == $value) {
                    $conditionsMet++;
                }

**Comment by AlexMordred** [comment]
Sorry, it's not possible.
