### ISSUE TITLE
Any chance this will be upgraded for framework v5.7.4

### ISSUE THREAD

**Issue by SiNi-Si** [voerro/laravel-visitor-tracker#14]
Looks like a great package

Thanks
Si

**Comment by AlexMordred** [comment]
Hi. This is similar to #9. I don't see why it wouldn't work in 5.7, but we need to update the package's `composer.json`. As I've mentioned in #9 I don't plan on doing so, but if you could fork this and submit a PR, I'd accept it and make a new release.
