### ISSUE TITLE
Default views not working, error :  there is no GROUP BY clause

### ISSUE THREAD

**Issue by shofin-islam** [voerro/laravel-visitor-tracker#3]
I am facing this problem, Can you please help
I have checked the migration file, there is no group === 

SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: SELECT COUNT(*) AS total FROM visitortracker_visits v LEFT JOIN users users ON users.id = v.user_id ORDER BY v.id DESC)

**Comment by AlexMordred** [comment]
Could you provide more details? What have you done and what page is this on?

**Comment by shofin-islam** [comment]
I have followed all the instruction properly except (Installation - Geoapi) as you mention. And then i just hit the route "visitortracker.summary", or any other route you mention and i always get this error. all Data is store inside my mysql database but default view not working. i have tried with url "/stats".... coulde you please check.

**Comment by AlexMordred** [comment]
Alright, thanks, I'll check it later.

**Comment by AlexMordred** [comment]
I've installed the package into a fresh Laravel project and did what you did. I don't get any errors, everything seems to work fine. Try to disable the strict mode in your project (config/database.php, 'strict' => false) or in your MySQL settings maybe?

**Comment by shofin-islam** [comment]
Thanks, this error has gone :) but another error 
View [layouts.dashboard] not found. (View: E:\XAMPP\htdocs\laravel\vendor\voerro\laravel-visitor-tracker\src\views\layout.blade.php) (View: E:\XAMPP\htdocs\laravel\vendor\voerro\laravel-visitor-tracker\src\views\layout.blade.php).
Need help.

**Comment by AlexMordred** [comment]
Please check the config file, there's an option to set the parent layout for the package's views. Change 'layouts.dashboard' to your layout's view.

**Comment by AlexMordred** [comment]
Please check the config file, there's an option to set the parent layout for the package's views. Change 'layouts.dashboard' to your layout's view.

**Comment by shofin-islam** [comment]
it works. Thanks a lot :)

**Comment by byte7584** [comment]
How did you solve it? I have the same error help please  =(

**Comment by shofin-islam** [comment]
@byte7584 
Change the master layout.
find the visitor tracker.php file inside config folder. then find 'layout' => ' put your layout example: frontend.master',

Hope it works :)
