### ISSUE TITLE
View [layouts.dashbard] not found

### ISSUE THREAD

**Issue by ganu** [voerro/laravel-visitor-tracker#4]
HI,

I can able to set up your package, after installing I am getting View [layouts.dashbard] not found while accessing stats url. I'm using laravel 5.5 version. I also tried to change layout option to "summary" in visitortracker.php file, that also didn't help me.

**Comment by AlexMordred** [comment]
Hi.

Well, changing the `layout` option should do it. Please, double check everything.

**Comment by ganu** [comment]
Hi,

 I have tried. Getting same error

**Comment by AlexMordred** [comment]
Try clearing the cache and restarting your server. Other than that I don't know what could be wrong as I've tested changing the option and it works fine.

**Comment by ganu** [comment]
Hi 
Im trying like this 'layout' => 'summary'
is this correct?

**Comment by AlexMordred** [comment]
If your layout file is located at `resources/views/summary.blade.php`, then yes.
