### ISSUE TITLE
Cant track geodata

### ISSUE THREAD

**Issue by sfuentes-90** [voerro/laravel-visitor-tracker#5]
I changed the .ENV values to simulate production enviroment

APP_NAME=Petsell
APP_ENV=staging
APP_KEY=base64:.............
APP_DEBUG=false
APP_LOG_LEVEL=debug
APP_URL=http://xxx.xxx.xxx.xxx (my real IP address)

but the database isn't logging geoip info (country, country code, lon, lat, city)

any help please, I already tried with both drivers (userinfo.io and freegeoip.net)

**Comment by AlexMordred** [comment]
Did it happen after you switched to production?

**Comment by sfuentes-90** [comment]
I was testing the geolocation in my testing enviroment... searching in the src files I deleted the if statement that prevent the geolocation in testing

thanks anyway

**Comment by AlexMordred** [comment]
Oh, I see. I'm glad you've figured it out.
