### ISSUE TITLE
How I can change to my API account?

### ISSUE THREAD

**Issue by mohamedsabil83** [voerro/laravel-visitor-tracker#8]
How I can change the API to my own one. The package count each link visited and reach the maximum request in just 7 days.

**Comment by AlexMordred** [comment]
You can change the geoip API in the config file. Although only 2 providers are supported.

**Comment by mohamedsabil83** [comment]
No, I mean keeping the **freegeoip.net** but adding my account details to allow more request.

BTW, **userinfo.io** returns wrong info while I'm in Saudi Arabia its feed I'm in the British Kingdom.

**Comment by AlexMordred** [comment]
I had to update the package since "freegeoip.net" has become "ipstack.com". Please update the package to v1.2.1 and publish the new config file. You can register with ipstack for free and enter the API key inside the package's config file. You might need to truncate (clear) the 'jobs' and 'failed_jobs' DB tables completely.

**Comment by mohamedsabil83** [comment]
Thank you man, I'll update it today.
Any advice on how to reduce requested from the same user like using cache somehow or any other way? cause the first time I use it, the requested amount end in 4 days while the site is new and there is not many people know about it.

**Comment by AlexMordred** [comment]
Hmm, there's no caching in the package. Maybe you could try replacing the package's middleware with your own. Ipstack gives you 10 000 requests per months for free, do you get that many visitors on a new site?

**Comment by mohamedsabil83** [comment]
yes, about 60 visitors and site stop cause returning an error cause amount ending.
maybe I let package count only homepage visitors and ignore the rest of page.
I'll take a look again to your middleware and see what I can do.
