### ISSUE TITLE
Will your package ever support Laravel 5.4?

### ISSUE THREAD

**Issue by YosefOberlander** [voerro/laravel-visitor-tracker#9]
Will your package ever support Laravel 5.4?

**Comment by vipertecpro** [comment]
Hello i'm using this package in laravel 5.6

**Comment by hcweb** [comment]
Hello, when I use it in laravel5.6, I get an error when accessing the route. I wonder if you have encountered this problem?
`
Illuminate \ Database \ QueryException (42000)
SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: SELECT COUNT(*) AS total FROM visitortracker_visits v LEFT JOIN users users ON users.id = v.user_id WHERE v.is_login_attempt != '1' AND v.is_bot != '1' AND v.is_ajax != '1' ORDER BY v.id DESC)
`

**Comment by AlexMordred** [comment]
@YosefOberlander Sorry for a very late reply. I think it should work in Laravel 5.4 (without any or too many changes), but you'd need to change the package's `composer.json` and edit the minimum required versions for `illuminate` packages. Unfortunately, I don't have much time and interest in this package right now.

@hcweb turning off the MySQL's strict mode in your project should work.
